# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import adsrank_pb2 as adsrank__pb2


class AdsrankStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScoreAdsUsingVector = channel.unary_unary(
                '/Adsrank/ScoreAdsUsingVector',
                request_serializer=adsrank__pb2.AdScoresRequest.SerializeToString,
                response_deserializer=adsrank__pb2.AdScoresResponse.FromString,
                )


class AdsrankServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ScoreAdsUsingVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdsrankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScoreAdsUsingVector': grpc.unary_unary_rpc_method_handler(
                    servicer.ScoreAdsUsingVector,
                    request_deserializer=adsrank__pb2.AdScoresRequest.FromString,
                    response_serializer=adsrank__pb2.AdScoresResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Adsrank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Adsrank(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScoreAdsUsingVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Adsrank/ScoreAdsUsingVector',
            adsrank__pb2.AdScoresRequest.SerializeToString,
            adsrank__pb2.AdScoresResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
